# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - canoacaicara

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x' # Mantendo sua versão do Node.js

      - name: npm install, build, and test in backend
        # Adicionado working-directory para rodar os comandos na pasta correta
        working-directory: ./backend
        run: |
          # Adicionada a flag --legacy-peer-deps para tentar resolver conflitos
          npm install --legacy-peer-deps
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # Alterado path para fazer upload apenas da pasta backend
          path: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          # O artefato (conteúdo da pasta backend) será baixado para a raiz

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E9B58D4280094CABA5A3CE5F7999136B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EB718ACAFE7C4CF8ABC05EB18E3EC584 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BE2A68274AE745F4BC248E9C2D27B643 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'canoacaicara'
          slot-name: 'Production'
          # O package: . agora funciona porque o artefato baixado contém apenas os arquivos do backend na raiz
          package: .
